name: Linux Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build (Linux)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc-14 \
          g++-14 \
          cmake \
          ninja-build \
          libasound2-dev \
          libpulse-dev \
          libwayland-dev \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxss-dev \
          libxcursor-dev \
          libxi-dev \
          libxdamage-dev \
          libxinerama-dev \
          libxtst-dev \
          libfreetype6-dev \
          libdbus-1-dev
        echo "CC=gcc-14" >> $GITHUB_ENV
        echo "CXX=g++-14" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Executable
      run: cmake --build build --config Release
